// Patients requests
GET http://localhost:5500/dashboard/patients
###

POST http://localhost:5500/dashboard/patients
Content-Type: application/json

{
    "firstname": "PatientA",
    "surname": "PatientA",
    "id_document": "22",
    "pathology": "anemia"
}
###

GET http://localhost:5500/dashboard/patients/1
###

PUT http://localhost:5500/dashboard/patients/1
Content-Type: application/json

{
    "pathology": "anemia"
}
###

DELETE http://localhost:5500/dashboard/patients/1
###